services:
  app:
    build: .
    ports:
      - "8501:8501"
    # environment:
    #   - DB_URI=postgresql://myuser:mypassword@postgres:5432/mydatabase
    # depends_on:
    #   - postgres
    volumes:
      - .:/app

#   postgres:
#     image: postgres:15
#     container_name: my-postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: mydatabase
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
